version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/ai_assist
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:16
    container_name: ai_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_assist
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

networks:
  app_net:

volumes:
  postgres_data: